package eu.jucy.gui;


import helpers.NLS;


/**
* This is a automatically generated file! DO NOT CHANGE!!
* see eu.jucy.releng.languages -> CreateLangFile for more details
*/
public class Lang {

	public static String
		 ActionMen
		,ActiveModeSettings
		,AddFolder
		,AddSoundNotificationToChatroom
		,AddSoundNotificationToPM
		,AddSoundOnNickInMainchat
		,AddToFavorites
		,Added
		,AddedFileViaMagnet
		,Address
		,Advanced
		,AdvancedFavHubProperties
		,All
		,AllXUsersOffline
		,AllowUsingUPnP
		,Appearance
		,AreYouSureYouWantToCloseJucy
		,AskBeforeShutdown
		,AutoConnect
		,AutoGrantSlot
		,AutomaticallyCheckForUpdates
		,AutomaticallyFollowRedirects
		,AutomaticallySearchForAlternates
		,AverageSpeed
		,Browse
		,BrowseFilelist
		,CSNATDetected
		,CSNOTWORKING
		,CSNoNATDetected
		,CSPassiveMode
		,CSToolTip
		,CSUNKNOWN
		,CSWORKING
		,ChatOnly
		,ChatOnlyDescription
		,ChooseFolder
		,Close
		,CloseAllPM
		,CloseAllPMDescription
		,CloseConnection
		,CloseDescription
		,Command
		,Connect
		,ConnectingTo
		,Connection
		,ConnectionSettings
		,Context
		,CopyAddressToClipboard
		,CopyMagnetLinkToClipboard
		,CopyNickToClipboard
		,CopyTTHToClipboard
		,DefaultAwayMessage
		,DefaultDownloadDirectory
		,DeleteLog
		,Description
		,DifferentFiles
		,Directory
		,Download
		,DownloadLimit
		,DownloadQueue
		,DownloadQueueDescription
		,DownloadTo
		,Downloaded
		,Downloading
		,Downloads
		,Duration
		,EMail
		,EnterSearch
		,Errors
		,ExactSize
		,ExcludedFiles
		,ExecuteAfterDownload
		,ExportAllLogs
		,ExportLog
		,ExternalWANIP
		,FavHubProperties
		,FavoriteHubs
		,FavoriteUsers
		,FavouriteFolders
		,FavouriteHubs
		,FavouriteHubsDescription
		,FavouriteUsers
		,FavouriteUsersDescription
		,FavouritesNicks
		,FileCol
		,FileColouring
		,FileDefaultCol
		,FileInDownloadCol
		,FileInShareCol
		,FileListMenu
		,FileMen
		,FileMultiUserCol
		,FileTFTooltip
		,FileTFTooltip2
		,FileType
		,Filelist
		,FilelistRefreshInterval
		,Filename
		,Files
		,FilesLeft
		,Find
		,FindDescription
		,FindExtensions
		,FindExtensionsDescription
		,Finished
		,FinishedDownloads
		,FinishedDownloadsDescription
		,FinishedHashingXinY
		,FinishedUploads
		,FinishedUploadsDescription
		,FirstRequest
		,FollowRedirect
		,FollowRedirectDescription
		,FontColour
		,ForceAttempt
		,GetFilelist
		,GrantExtraSlot
		,HasExtraSlotUntil
		,Help
		,HideToolbar
		,High
		,Highest
		,Hub
		,HubAddedToFavorites
		,HubExplaCommands
		,HubIsAlreadyFavorite
		,HubMenu
		,Hubs
		,IP
		,IPPrefixMod
		,Identification
		,ImportFromDCPP
		,ImportFromDCPPDescription
		,IncludedFiles
		,IncomingConnectionSettings
		,InvalidAddress
		,LastRequest
		,LineSpeed
		,LogFeed
		,LogMainchat
		,LogPM
		,LogViewer
		,LogViewerDescription
		,Logging
		,Logs
		,LogsDescription
		,Low
		,Lowest
		,MatchQueue
		,MaxHashSpeed
		,Maximize
		,MaximumSimultaneousDownloads
		,MinimizeOnStart
		,MinimizeToTray
		,MiscHubTab
		,MiscPrefPage
		,MoveDown
		,MoveRename
		,MoveUp
		,Name
		,NameUnderWhichTheOthersSeeTheDirectory
		,New
		,Next
		,Nick
		,NickColourer
		,No
		,NoUsers
		,Normal
		,NormalNicks
		,Online
		,OnlyUsersWithFreeSlots
		,OnlyWhereIAmOp
		,OpenFileList
		,OpenOwnList
		,OpenPMinForeground
		,OperatorNicks
		,OverrideProtocolCodepage
		,OwnNick
		,Parameter
		,Password
		,Path
		,Paused
		,PersonalInformation
		,PopupDissappearanceTime
		,Preferences
		,PreferencesDescription
		,PrimaryDownloadColour
		,PrimaryUploadColour
		,Priority
		,ProgressView
		,Properties
		,PruneAllOlderThan
		,PublicHubs
		,Question
		,QuickConnect
		,QuickConnectDescription
		,Ratio
		,RatioDesc
		,ReAddUserToFile
		,ReceivedResults
		,Reconnect
		,ReconnectDescription
		,RedirectReceived
		,RefreshFilelist
		,Remove
		,RemoveDescription
		,RemoveFileFromQueue
		,RemoveFromFavorites
		,RemoveUserFromDQ
		,RemoveUserFromFile
		,Rename
		,RequestsReceived
		,Restore
		,RevokeGrantedSlot
		,Search
		,SearchDescription
		,SearchFor
		,SearchForAlternates
		,SearchMenu
		,SearchOptions
		,SecondaryDownloadColour
		,SecondaryUploadColour
		,SelectFont
		,SendOnceForEachUser
		,SendPrivateMessage
		,Separator
		,SetAwayMessageOnMinimize
		,SetPriority
		,ShareHiddenFiles
		,Shared
		,SharedDirectorys
		,Sharing
		,ShowChatterJoins
		,ShowConnStatus
		,ShowDownSpeed
		,ShowDownTotal
		,ShowFavJoins
		,ShowHubs
		,ShowJoins
		,ShowPMInMainchat
		,ShowPOPUPonChatroom
		,ShowPOPUPonNickinMC
		,ShowPOPUPonPM
		,ShowSharesize
		,ShowSidebar
		,ShowSlots
		,ShowUpSpeed
		,ShowUpTotal
		,Size
		,SizeLeft
		,SlotReceived
		,Slots
		,Speed
		,Started
		,Status
		,StatusBarPrefPage
		,StoredPM
		,StoredPMUser
		,SystemLog
		,TCPPort
		,TLSTCPPort
		,TTHRoot
		,Tag
		,TextModifications
		,TimeLastSeen
		,TimeLeft
		,TimeStamps
		,ToggleToolbar
		,ToggleToolbarDescription
		,TotalDownloaded
		,TotalElements
		,TotalFiles
		,TotalMessages
		,TotalSize
		,TotalSizeLeft
		,TotalSizeNoParm
		,TotalTimeLeft
		,Transfers
		,TransfersTable
		,Type
		,UDPPort
		,URLColour
		,URLFont
		,URLHighlighting
		,UnfinishedDownloadsDirectory
		,Unlimited
		,Update
		,UpdateAvailable
		,UpdateAvailableMessage
		,UpdateDescription
		,UploadLimit
		,UploadQueue
		,UploadQueueDescription
		,UploadSlots
		,UseAlternativeTabs
		,UsePassiveMode
		,UseTLSIfPossible
		,User
		,UserCommand
		,UserCommands
		,UserDescription
		,UserJoins
		,UserMenu
		,UserOnline
		,UserParts
		,UserTable
		,Users
		,View
		,VirtualName
		,WindowBackgroundColour
		,XOfYUsersOnline
		,Yes ;
	
	static {
		try {
			NLS.load("nl.gui", Lang.class);
		} catch(RuntimeException re) {
			re.printStackTrace();
		}
	}
}