/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeHasher */

#ifndef _Included_NativeHasher
#define _Included_NativeHasher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeHasher
 * Method:    hashBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_NativeHasher_hashBytes
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
