package uc;

import uc.DCClient;
import helpers.NLS;


/**
* This is a automatically generated file! DO NOT CHANGE!!
* see eu.jucy.releng.languages -> CreateLangFile for more details
*/
public class LanguageKeys {

	public static String
		 ActionMen
		,Active
		,Add
		,AddFolder
		,AddToFavorites
		,Added
		,Address
		,AddressCouldNotBeResolved
		,All
		,AllXUsersOffline
		,AllowUsingUPnP
		,AtLeast
		,AtMost
		,AutoConnect
		,AutoGrantSlot
		,Average
		,Browse
		,BrowseFilelist
		,CDCheckFirewall
		,CDCheckForwardedPorts
		,CDCheckTCP
		,CDCheckUDP
		,CDDeterminedIPOverWeb
		,CDUPnPNotPresent
		,CDUPnPNotWorking
		,CSNATDetected
		,CSNOTWORKING
		,CSNoNATDetected
		,CSPassiveMode
		,CSToolTip
		,CSUNKNOWN
		,CSWORKING
		,ChatOnly
		,ChooseFolder
		,CloseConnection
		,Closed
		,Command
		,ConfigurePublicHubLists
		,Connect
		,Connected
		,Connecting
		,ConnectingTo
		,Connection
		,ConnectionSettings
		,ConnectionTimeout
		,Context
		,CopyAddressToClipboard
		,CopyNickToClipboard
		,CopyTTHToClipboard
		,Count
		,CreateHub
		,DefaultAwayMessage
		,DefaultDownloadDirectory
		,Description
		,Directories
		,Directory
		,DirectoryForLogs
		,Disconnected
		,Download
		,DownloadAndOpen
		,DownloadLimit
		,DownloadTo
		,Downloaded
		,Downloading
		,Downloads
		,EMail
		,Edit
		,EditTheHublist
		,EnterAddressOfTheHublist
		,Equals
		,Errors
		,ExactSize
		,ExecuteAfterDownload
		,ExternalWANIP
		,FavHubProperties
		,FavoriteHubs
		,FavoriteUsers
		,File
		,FileListMenu
		,FileMen
		,FileType
		,FilelistRefreshAlreadyInProgress
		,Filename
		,Files
		,Find
		,FinishedFilelistRefresh
		,FinishedHashingXinY
		,ForceAttempt
		,GetFilelist
		,GrantExtraSlot
		,HasExtraSlotUntil
		,Help
		,Hub
		,HubAddedToFavorites
		,HubExplaCommands
		,HubIsAlreadyFavorite
		,HubIsFull
		,HubMenu
		,HubRequestedPassword
		,Hublist
		,Hubs
		,IP
		,Identification
		,Idle
		,IncomingConnectionSettings
		,IsFavoriteUser
		,LastChange
		,Limits
		,LineSpeed
		,LoadHublist
		,LogFeed
		,LogMainchat
		,LogPM
		,LoggedIn
		,LoginTimeout
		,MatchQueue
		,MatchedXFilesWithUserY
		,MaximumSimultaneousDownloads
		,MinimizeToTray
		,MoveDown
		,MoveRename
		,MoveUp
		,Name
		,NameUnderWhichTheOthersSeeTheDirectory
		,New
		,Next
		,Nick
		,No
		,NoUsers
		,OK
		,Online
		,OnlyUsersWithFreeSlots
		,OnlyWhereIAmOp
		,OpenFileList
		,OpenOwnList
		,Parameter
		,Password
		,Path
		,PersonalInformation
		,PrimaryDownloadColour
		,PrimaryUploadColour
		,Priority
		,Properties
		,PublicHubs
		,PublicHubsList
		,QuickConnect
		,Ratio
		,ReAddUserToFile
		,Reconnecting
		,RedirectReceived
		,RefreshFilelist
		,Remove
		,RemoveFromFavorites
		,RemoveUserFromDQ
		,RemoveUserFromFile
		,Rename
		,STA11HubFull
		,STA12HubDisabled
		,STA21NickInvalid
		,STA22NickTaken
		,STA23InvalidPassword
		,STA24CIDtaken
		,STA25AccessToCommandDenied
		,STA26RegisteredUsersOnly
		,STA27InvalidPIDSupplied
		,STA31PermanentlyBanned
		,STA32TemporarilyBanned
		,STA41TransferProtocolUnsupported
		,STA42DirectConnectionFailed
		,STA43RequiredINFfieldBad
		,STA43RequiredINFfieldMissing
		,STA44InvalidState
		,STA45RequiredFeatureMissing
		,STA46InvalidIPSupplied
		,STA47NoHashSupportOverlapHub
		,STA51FileNotAvailable
		,STA52FilePartNotAvailable
		,STA53SlotsFull
		,STA54NoHashSupportOverlapClient
		,Search
		,SearchFor
		,SearchForAlternates
		,SearchMenu
		,SearchOptions
		,SearchString
		,SecondaryDownloadColour
		,SecondaryUploadColour
		,SelectFont
		,SendOnceForEachUser
		,SendPrivateMessage
		,SendingPassword
		,Separator
		,Server
		,SetPriority
		,Settings
		,ShareHiddenFiles
		,Shared
		,SharedDirectorys
		,Sharing
		,ShowSidebar
		,Size
		,Slots
		,Speed
		,StartedRefreshingTheFilelist
		,Status
		,SystemLog
		,TCPPort
		,TTHRoot
		,Tag
		,Time
		,TimeLastSeen
		,TimeLeft
		,TotalSizeNoParm
		,TransferFinished
		,Type
		,UDPPort
		,UnfinishedDownloadsDirectory
		,UploadSlots
		,UsePassiveMode
		,User
		,UserCommand
		,UserCommands
		,UserConnected
		,UserDescription
		,UserDisconnected
		,UserLeft
		,UserMenu
		,UserOffline
		,UserOnline
		,Users
		,View
		,VirtualName
		,WaitingForConnect
		,XOfYUsersOnline
		,Yes ;
	
	static {
		try {
			NLS.load("nl.language", LanguageKeys.class);
		} catch(RuntimeException re) {
			DCClient.logger.warn(re,re);
		}
	}
}